__default__:
    q:  broad
    h_vmem: 20G
    h_rt:   5:0:0
    pe: smp 2
    binding:    linear:1

runSvaba:
    h_vmem:    3G  # per-core-mem
    h_rt:    300:00:00
    pe: smp 4
    binding:    linear:4
    
barcodeRescue:
    h_vmem: 20G
    h_rt:   300:0:0
    pe: smp 4

combineSvabaTitan:
    h_vmem: 40G
    h_rt:   300:0:0
    pe: smp 4

plotSvabaTitan:
    h_vmem: 10G
    h_rt:   300:0:0
    pe: smp 1
