samples: #format is sample_name: /path/to/sample.bam for both tumors and normals
   #DTRCC10_Rkidney:  /mnt/storage/labs/sviswanathan/tRCC_data/bamlinks/linked_reads/DTRCC10_Rkidney/
   #DTRCC_10_Blood:  /mnt/storage/labs/sviswanathan/tRCC_data/bamlinks/linked_reads/DTRCC10_Blood/
   #DTRCC8_Lkidney:  /mnt/storage/labs/sviswanathan/tRCC_data/bamlinks/linked_reads/DTRCC8_Lkidney/
   #DTRCC_8_Blood:  /mnt/storage/labs/sviswanathan/tRCC_data/bamlinks/linked_reads/DTRCC8_Blood/
   DTRCC5_LPAnode:  /mnt/storage/labs/sviswanathan/tRCC_data/bamlinks/linked_reads/DTRCC5_LPAnode/H2K57CCX2_DTRCC5_LPAnode/outs/
   DTRCC5_Blood: /mnt/storage/labs/sviswanathan/tRCC_data/bamlinks/linked_reads/DTRCC_5_Blood/H2K57CCX2_DTRCC_5_Blood/outs/

pairings: #format is tumor: matched_normal
  DTRCC5_LPAnode: DTRCC5_Blood
  #DTRCC10_Rkidney: DTRCC_10_Blood
  #DTRCC8_Lkidney: DTRCC_8_Blood
