## path to tools

#samTools: /mnt/storage/apps/samtools/1.9/bin/samtools
#bcfTools: /mnt/storage/apps/bcftools/1.9/bin/bcftools

#samTools: /mnt/storage/apps/samtools/1.9/bin/samtools
bcfTools: /mnt/storage/apps/bcftools/1.15.1/bin/bcftools

samTools: /mnt/storage/apps/samtools/1.8/bin/samtools
#bcfTools: /mnt/storage/apps/bcftools/1.9/bin/bcftools

#bcfTools: /mnt/storage/apps/bcftools/1.8/bin/bcftools # not in argos anymore

svaba_exe:  /home/ma1111/tools/svaba/bin/svaba

## path to scripts ##
#Download these files and set paths below
readCounterScript: /home/ma1111/tools/hmmcopy_utils/bin/readCounter  #/path/to/readCounter
ichorCNA_rscript: /home/ma1111/tools/ichorCNA/scripts/runIchorCNA.R  #/path/to/ichorCNA.R - think it is called runIchorCNA.R now!

#ichorCNA_libdir: home/ma1111/tools/ichorCNA/ichorCNA_code  #/path/to/ichorCNA_code - this is optional, point to the R dir of ichorCNA

pyCountScript: /home/ma1111/tools/TitanCNA_SV_WGS/code/countPysam.py  #code/countPysam.py
TitanCNA_rscript: /home/ma1111/tools/TitanCNA/scripts/R_scripts/titanCNA.R    #../R_scripts/titanCNA.R
TitanCNA_combineTitanIchorCNA: /home/ma1111/tools/TitanCNA_SV_WGS/code/combineTITAN-ichor.R  #code/combineTITAN-ichor.R
TitanCNA_selectSolutionRscript: /home/ma1111/tools/TitanCNA/scripts/R_scripts/selectSolution.R #../R_scripts/selectSolution.R

TitanCNA_libdir: /home/ma1111/tools/TitanCNA
ichorCNA_libdir: /home/ma1111/tools/ichorCNA

## path to scripts ##
svaba_funcs:  /home/ma1111/tools/TitanCNA_SV_WGS/code/svaba_utils.R
plot_funcs:  /home/ma1111/tools/TitanCNA_SV_WGS/code/plotting.R
combineSVCN_script:  /home/ma1111/tools/TitanCNA_SV_WGS/code/combineSVABAandTITAN.R
plotSVCN_script:  /home/ma1111/tools/TitanCNA_SV_WGS/code/plotTitanSvaba.R
plotSVCNichor_script: /home/ma1111/tools/TitanCNA_SV_WGS/code/plotIchorSvaba.R
plotCircos_script: /home/ma1111/tools/TitanCNA_SV_WGS/code/create_circosPlot.R


## reference settings and paths to reference files ##
genomeBuild: hg38  # Use "None" if hg19
genomeStyle: UCSC
refFasta: /mnt/storage/labs/sviswanathan/GATK_ref/Homo_sapiens_assembly38.fasta #/path/to/Homo_sapiens_assembly38.fasta
#refFasta: /mnt/storage/labs/sviswanathan/GATK_ref/cz_ref/longranger/refdata-GRCh38-2.1.0/fasta/genome.fa
snpVCF: /mnt/storage/labs/sviswanathan/GATK_ref/hapmap_3.3.hg38.vcf.gz #/path/to/hapmap_3.3.hg38.vcf.gz
#ichorCNA_exons: NULL #check this as Imran had intervals.bed files
cytobandFile: /home/ma1111/tools/ichorCNA/inst/extdata/cytoBand_hg38.txt # only need if hg38
centromere:  /home/ma1111/tools/ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt

#sex:  male   ## use None if both females and males are in sample set
sex: female

## params for each step ##

## read depth params ##
# use this for NCBI chr naming
#chrs: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y 
# use this for UCSC chr naming
chrs: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY 
binSize:  10000 #10000 used for females and males, default was 50000

## ichorCNA params ##
#Need the hg38 wig files - set paths here!
# wig files are already in the downloaded ichorCNA in inst and extdata

# must use map wig file corresponding to same binSize (required)
# use panel matching same bin size (optional)
# ichorCNA_normalPanel: /home/ma1111/tools/ichorCNA/inst/extdata/HD_ULP_PoN_hg38_1Mb_median_normAutosome_median.rds
ichorCNA_exons: /home/ma1111/tools/baitsets/S07604514_hs_hg38_SureSelect_Human_All_Exon_V6_r2/S07604514_AllTracks.bed # set this to NULL if running on WGS data

# must use gc wig file corresponding to same binSize (required)
ichorCNA_gcWig: /home/ma1111/tools/ichorCNA/inst/extdata/gc_hg38_10kb.wig
# must use map wig file corresponding to same binSize (required)
ichorCNA_mapWig:  /home/ma1111/tools/ichorCNA/inst/extdata/map_hg38_10kb.wig
# use bed file if sample has targeted regions, eg. exome data (optional)
ichorCNA_repTimeWig: /home/ma1111/tools/ichorCNA/inst/extdata/RepTiming_hg38_10kb.wig
ichorCNA_centromere: /home/ma1111/tools/ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt


## getAllelCounts params
map_quality:  10
base_quality: 10
vcf_quality:  100


ichorCNA_chrs:  paste0('chr', c(1:22, \"X\"))

# chrs used for training ichorCNA parameters, e.g. tumor fraction. 
ichorCNA_chrTrain:  paste0('chr', c(1:22))
# non-tumor fraction parameter restart values; higher values should be included for cfDNA
ichorCNA_normal:  c(0.5)
# ploidy parameter restart values
ichorCNA_ploidy:  c(2,3,4)
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
# states to use for subclonal CN
ichorCNA_scStates:  c(1,3)
# penalize subclonal events - n-fold multiplier; n=1 for no penalty,  
ichorCNA_scPenalty: 1
# set maximum copy number to use
ichorCNA_maxCN:  8
ichorCNA_likModel: t  # if multisample, use "gauss"

# TRUE/FALSE to include homozygous deletion state
ichorCNA_includeHOMD: TRUE
# control segmentation - higher (e.g. 0.9999999) leads to higher specificity and fewer segments
ichorCNA_minMapScore: 0.75
ichorCNA_maxFracGenomeSubclone: 0.5
ichorCNA_maxFracCNASubclone: 0.7
# Ignore subclonal analysis when initial normal setting >= this value
ichorCNA_normal2IgnoreSC: 0.90
# lower (e.g. 0.99) leads to higher sensitivity and more segments
ichorCNA_txnE:  0.9999
# control segmentation - higher (e.g. 10000000) leads to higher specificity and fewer segments
# lower (e.g. 100) leads to higher sensitivity and more segments
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  pdf
ichorCNA_plotYlim:  c(-2,4)


## TitanCNA params
TitanCNA_maxNumClonalClusters: 3
TitanCNA_chrs:  c(1:22, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 4
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  10000
TitanCNA_alphaR:  10000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_numCores: 1

## Combine TitanCNA & ichorCNA
mergeIchorHOMD: FALSE  # consider setting to TRUE when working with pure tumor

## SVABA settings ##
svaba_dbSNPindelVCF:  /mnt/storage/labs/sviswanathan/GATK_ref/Homo_sapiens_assembly38.known_indels.vcf.gz #/path/to/resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf.gz
svaba_minSPAN:  10000
svaba_minInversionSPAN: 1000
svaba_numThreads: 4 #make sure this is okay

##Svaba Plotting parameters ##
plot_zoom:  FALSE
plot_chrs:  c(1:22, \"X\") # "None" will also plot all chromosomes
plot_startPos:  None
plot_endPos:  None
plot_geneFile:  data/gene_list_72.txt ## include list of genes to annotate on plot
plot_ylim:  c(-2,4)
plot_size:  c(8,4)
plot_type:  titan ## titan - will include haplotype fraction
plot_format:  png
plot_ichor_units: logratio


