#samples.yaml for M2_filter.snakefile

base_file_name: 
  DTRCC_12: /home/mi724/Tools/Mutect2_Snakemake/Samples12_16/Sample12Tumorbam.list
  DTRCC_12_Blood: /home/mi724/Tools/Mutect2_Snakemake/Samples12_16/Sample12Normalbam.list
  RTRCC_16: /home/mi724/Tools/Mutect2_Snakemake/Samples12_16/Sample16Tumorbam.list
  RTRCC_16_PBMC: /home/mi724/Tools/Mutect2_Snakemake/Samples12_16/Sample16Normalbam.list


normals:
  DTRCC_12: DTRCC_12_Blood
  RTRCC_16: RTRCC_16_PBMC
