##Config file containing information for the mutect2.snakefile

## Tools Path
gatk_path: /mnt/storage/apps/gatk-4.3.0.0/gatk
java: /usr/bin/java
tabix: /usr/bin/tabix
picard_jar: /home/ma1111/tools/picard.jar

## Path to reference files
reference_genome: /mnt/storage/labs/sviswanathan/GATK_ref/Homo_sapiens_assembly38.fasta
reference_dict: /mnt/storage/labs/sviswanathan/GATK_ref/Homo_sapiens_assembly38.dict
germline_resource: /mnt/storage/labs/sviswanathan/GATK_ref/cz_ref/hg38_pon/af-only-gnomad.hg38.vcf.gz
panel_of_normals: /mnt/storage/labs/sviswanathan/GATK_ref/cz_ref/hg38_pon/M2PoN_4.0_WGS_for_public.vcf
variants_for_contamination: /mnt/storage/labs/sviswanathan/GATK_ref/cz_ref/mutect2-contamination-variants.hg38_primary.vcf.gz
interval_list: /mnt/storage/labs/sviswanathan/GATK_ref/cz_ref/wgs_metrics_intervals.interval_list
realignment_index_bundle: /mnt/storage/labs/sviswanathan/GATK_ref/cz_ref/Homo_sapiens_assembly38.index_bundle
cytoBand_list: /mnt/storage/labs/sviswanathan/GATK_ref/cz_ref/cytoBand_acen.hg38.interval_list

#Interval chromosomes
chromosomes: ['chr1','chr2','chr3','chr4','chr5','chr6','chr7','chr8','chr9','chr10','chr11','chr12','chr13','chr14','chr15','chr16','chr17','chr18','chr19','chr20','chr21','chr22','chrX']

# M2 Extra Args logic
m2_extra_args: True
