#!/bin/bash
source /etc/profile
#$ -S /bin/bash
#$ -pe pvm 4
module load use.own
source /mnt/storage/apps/anaconda3/etc/profile.d/conda.sh
conda activate base
module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/python-3.7.3-gcc-5.4.0-cjw3ewa
module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/tophat-2.1.2-gcc-5.4.0-dkzyikw
module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/samtools-1.9-gcc-5.4.0-jjq5nua
module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/bowtie2-2.3.5-gcc-5.4.0-cxapxq6
module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/bedtools2-2.27.1-gcc-5.4.0-iouh4nk
module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/star-2.7.2b-gcc-5.4.0-fqvrpgi
module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/rsem-1.3.1-gcc-5.4.0-ml3p6ok
python ASE_example.py
